version: "3.8"
services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data
    command: redis-server --appendonly yes
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: shimeji2214
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-api
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
      - gem_data:/usr/local/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
      RAILS_ENV: development
  front:
    build:
      context: ./front
      dockerfile: Dockerfile-front
    command: sh -c "cd schedule-app-front && npm run dev"
    volumes:
      - ./front:/usr/src/app
    depends_on:
      - api
    ports:
      - "8000:3000"

volumes:
  redis-data:
  mysql-data:
  gem_data:
  node_modules:
